// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcttSu89FMt0OkX9xJlQQEzMZZYY1TQPk',
    appId: '1:90155757805:web:2759601cfe312859ad9ce4',
    messagingSenderId: '90155757805',
    projectId: 'fintech-app-2ff03',
    authDomain: 'fintech-app-2ff03.firebaseapp.com',
    storageBucket: 'fintech-app-2ff03.firebasestorage.app',
    measurementId: 'G-XVM0BYJSER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuXEmPWywt00SPjqCbFVjNkIMoxnQQsMs',
    appId: '1:90155757805:android:5cb0e81de5214ef9ad9ce4',
    messagingSenderId: '90155757805',
    projectId: 'fintech-app-2ff03',
    storageBucket: 'fintech-app-2ff03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0CNht94RdG8l-KyFzGjR7GKaM9SvMPU',
    appId: '1:90155757805:ios:56a7699d4f6028b6ad9ce4',
    messagingSenderId: '90155757805',
    projectId: 'fintech-app-2ff03',
    storageBucket: 'fintech-app-2ff03.firebasestorage.app',
    iosClientId: '90155757805-ul3gbscu8ap9tga8mi4tggqa5ra37nbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintechDashboardApp',
  );

}